global using System;
global using System.Collections.Generic;
global using System.Linq;
global using BankPhase = DragonGlare.Domain.BankPhase;
global using BattleEncounter = DragonGlare.Domain.Battle.BattleEncounter;
global using BattleActionType = DragonGlare.Domain.BattleActionType;
global using BattleFlowState = DragonGlare.Domain.BattleFlowState;
global using BattleStatusEffect = DragonGlare.Domain.BattleStatusEffect;
global using BattleVisualCue = DragonGlare.Domain.BattleVisualCue;
global using BattleService = DragonGlare.Services.BattleService;
global using BankTransactionResult = DragonGlare.Services.BankTransactionResult;
global using EquipmentSlot = DragonGlare.Domain.EquipmentSlot;
global using FieldMapId = DragonGlare.Domain.FieldMapId;
global using GameContent = DragonGlare.Data.GameContent;
global using GameState = DragonGlare.Domain.GameState;
global using LaunchSettings = DragonGlare.Domain.Startup.LaunchSettings;
global using LaunchDisplayMode = DragonGlare.Domain.LaunchDisplayMode;
global using MapFactory = DragonGlare.Services.MapFactory;
global using PlayerFacingDirection = DragonGlare.Domain.PlayerFacingDirection;
global using SaveDataMapper = DragonGlare.Persistence.SaveDataMapper;
global using SaveManager = DragonGlare.Persistence.SaveManager;
global using SaveSlotSelectionMode = DragonGlare.Domain.SaveSlotSelectionMode;
global using SaveSlotState = DragonGlare.Persistence.SaveSlotState;
global using SaveSlotSummary = DragonGlare.Persistence.SaveSlotSummary;
global using ShopMenuEntryType = DragonGlare.Domain.ShopMenuEntryType;
global using ShopPhase = DragonGlare.Domain.ShopPhase;
global using SoundEffect = DragonGlare.Domain.SoundEffect;
global using UiLanguage = DragonGlare.Domain.UiLanguage;
