global using DragonGlare;
global using DragonGlare.Data;
global using DragonGlare.Domain.Battle;
global using DragonGlare.Domain.Commerce;
global using DragonGlare.Domain.Field;
global using DragonGlare.Domain.Items;
global using DragonGlare.Domain.Player;
global using DragonGlare.Persistence;
global using DragonGlare.Security;
global using DragonGlare.Services;
global using BankPhase = DragonGlare.Domain.BankPhase;
global using BattleActionType = DragonGlare.Domain.BattleActionType;
global using BattleFlowState = DragonGlare.Domain.BattleFlowState;
global using BattleStatusEffect = DragonGlare.Domain.BattleStatusEffect;
global using BattleVisualCue = DragonGlare.Domain.BattleVisualCue;
global using EquipmentSlot = DragonGlare.Domain.EquipmentSlot;
global using FieldMapId = DragonGlare.Domain.FieldMapId;
global using GameState = DragonGlare.Domain.GameState;
global using LaunchDisplayMode = DragonGlare.Domain.LaunchDisplayMode;
global using PlayerFacingDirection = DragonGlare.Domain.PlayerFacingDirection;
global using SaveSlotSelectionMode = DragonGlare.Domain.SaveSlotSelectionMode;
global using ShopMenuEntryType = DragonGlare.Domain.ShopMenuEntryType;
global using ShopPhase = DragonGlare.Domain.ShopPhase;
global using UiLanguage = DragonGlare.Domain.UiLanguage;
